// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class TokenRecord {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TokenRecord {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTokenRecord(bb:flatbuffers.ByteBuffer, obj?:TokenRecord):TokenRecord {
  return (obj || new TokenRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTokenRecord(bb:flatbuffers.ByteBuffer, obj?:TokenRecord):TokenRecord {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TokenRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():string|null
timestamp(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
timestamp(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

apiType():string|null
apiType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
apiType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

route():string|null
route(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
route(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

model():string|null
model(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
model(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

inputTokens():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

outputTokens():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

totalTokens():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

responseTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

statusCode():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

isStream():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startTokenRecord(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addTimestamp(builder:flatbuffers.Builder, timestampOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, timestampOffset, 0);
}

static addApiType(builder:flatbuffers.Builder, apiTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, apiTypeOffset, 0);
}

static addRoute(builder:flatbuffers.Builder, routeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, routeOffset, 0);
}

static addModel(builder:flatbuffers.Builder, modelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, modelOffset, 0);
}

static addInputTokens(builder:flatbuffers.Builder, inputTokens:bigint) {
  builder.addFieldInt64(4, inputTokens, BigInt('0'));
}

static addOutputTokens(builder:flatbuffers.Builder, outputTokens:bigint) {
  builder.addFieldInt64(5, outputTokens, BigInt('0'));
}

static addTotalTokens(builder:flatbuffers.Builder, totalTokens:bigint) {
  builder.addFieldInt64(6, totalTokens, BigInt('0'));
}

static addResponseTime(builder:flatbuffers.Builder, responseTime:bigint) {
  builder.addFieldInt64(7, responseTime, BigInt('0'));
}

static addStatusCode(builder:flatbuffers.Builder, statusCode:number) {
  builder.addFieldInt32(8, statusCode, 0);
}

static addIsStream(builder:flatbuffers.Builder, isStream:boolean) {
  builder.addFieldInt8(9, +isStream, +false);
}

static endTokenRecord(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTokenRecord(builder:flatbuffers.Builder, timestampOffset:flatbuffers.Offset, apiTypeOffset:flatbuffers.Offset, routeOffset:flatbuffers.Offset, modelOffset:flatbuffers.Offset, inputTokens:bigint, outputTokens:bigint, totalTokens:bigint, responseTime:bigint, statusCode:number, isStream:boolean):flatbuffers.Offset {
  TokenRecord.startTokenRecord(builder);
  TokenRecord.addTimestamp(builder, timestampOffset);
  TokenRecord.addApiType(builder, apiTypeOffset);
  TokenRecord.addRoute(builder, routeOffset);
  TokenRecord.addModel(builder, modelOffset);
  TokenRecord.addInputTokens(builder, inputTokens);
  TokenRecord.addOutputTokens(builder, outputTokens);
  TokenRecord.addTotalTokens(builder, totalTokens);
  TokenRecord.addResponseTime(builder, responseTime);
  TokenRecord.addStatusCode(builder, statusCode);
  TokenRecord.addIsStream(builder, isStream);
  return TokenRecord.endTokenRecord(builder);
}
}
